#!/usr/bin/env bash
set -e

echo "[dotfiles] Setting up dotfiles..."

# Check if the dotfiles are cloned and if not clone them
if [ -d ~/.dotfiles/ ]; then
    echo "[dotfiles] ~/.dotfiles directory already exists! Make sure to git pull to ensure it is up to date"
else
    git clone https://github.com/bryanaknight/dotfiles.git ~/.dotfiles
fi

# Install Oh My Zsh
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    read -p "[dotfiles] Do you wish to install Oh-My-ZSH? " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        /bin/bash -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
else
    echo "[dotfiles] Installing oh my zsh"
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

# TODO install vim plug

# Symlink dotfiles

# Link dotfiles
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
    read -p "[dotfiles] Do you wish to link your dotfiles? (old ones will be backed up to ~/dotfiles_old) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        mkdir -p ~/dotfiles_old

        files=( ".vimrc" ".zshrc" )

        for file in "${files[@]}"; do
            if [ -f ~/$file ]; then
                cp -L ~/$file ~/dotfiles_old/$file
                rm -f ~/$file
            fi
            ln -s ~/.dotfiles/$file ~/$file
        done
    fi

else
    echo "[dotfiles] Linking dotfiles"
    mkdir -p ~/dotfiles_old

    files=( ".vimrc" ".zshrc" )

    for file in "${files[@]}"; do
        if [ -f ~/$file ]; then
            cp -L ~/$file ~/dotfiles_old/$file
            rm -f ~/$file
        fi
        ln -s ~/.dotfiles/$file ~/$file
    done

    echo "[dotfiles] Setting up auto-suggestions"
    git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
fi

echo "[dotfiles] Done setting up dotfiles..."
